trigger:
- master
- develop

pool:
  vmImage: ubuntu-20.04

variables:
  location: "West Europe"
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]
  isPullRequestToDev: $[and(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/develop'))]
  isPullRequestToMaster: $[and(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/master'))]
  isManual: $[eq(variables['Build.Reason'], 'Manual')]

  ci_dev_condition: $[or(eq(variables.isPullRequestToDev, true), eq(variables.isDev, true), eq(variables.isManual, true))]
  cd_dev_condition: $[and(eq(variables.isPullRequest, false), eq(variables.isDev, true))]

  ci_test_condition: $[or(eq(variables.isMaster, true), eq(variables.isPullRequestToMaster, true))]
  cd_test_condition: $[and(eq(variables.isMaster, true), eq(variables.isPullRequest, false))]

  cd_prod_condition: $[and(eq(variables.isMaster, true), eq(variables.isPullRequest, false))]

resources:
  repositories:
    - repository: templates
      type: git
      name: Cellows/cellows-pipeline-templates

stages:

# ENVIRONMENT : DEVELOPMENT
  - template: stage-ci-angular-package.yml@templates
    parameters:
      stageName: CI_Angular_DEV
      condition: and(succeeded(), eq(variables.ci_dev_condition, true))
      projectsToPublish:
        - name: core

  - template: stage-cd-npm-package.yml@templates
    parameters:
      stageName: CD_NPM_PACKAGE_DEV
      condition: eq(variables.cd_dev_condition, true)
      dependsOn:  CI_Angular_DEV
      environment: Dev
      projectsToPublish:
        - name: core
      token: $(TOKEN)

# ENVIRONMENT : TEST
  - template: stage-ci-angular-package.yml@templates
    parameters:
      stageName: CI_Angular_TEST
      condition: and(succeeded(), eq(variables.ci_test_condition, true))
      projectsToPublish:
        - name: core

  - template: stage-cd-npm-package.yml@templates
    parameters:
      stageName: CD_NPM_PACKAGE_TEST
      condition: eq(variables.cd_test_condition, true)
      dependsOn:  CI_Angular_TEST
      environment: Test
      projectsToPublish:
        - name: core
      token: $(TOKEN)
